finish gui there were a lot of problems with it LMAO the info_packages function still prints to the terminal, IDK how to fix it

diff --git a/cinna b/cinna
--- a/cinna
+++ b/cinna
@@ -6,6 +6,7 @@
 #  \___|_|_| |_|_| |_|\__,_|
 # "That Weird Package Manager"
 
+gui="false"
 dependencies=("wget" "curl")
 
 command_exists() {
@@ -69,13 +70,20 @@ function check_for_updates() {
         if [[ "$latest_version" > "$VERSION" ]]; then
             echo -e "${YELLOW}A new version of Cinna is available: $latest_version.${NC}"
             echo -e "You can update Cinna using 'cinna update'."
+            exit_code="CN_UPD"
         elif [[ "$latest_version" < "$VERSION" ]]; then
             echo -e "${YELLOW}You're on a development version! You're using $VERSION (latest: $latest_version)${NC}"
             echo -e "Warning: Running 'cinna update' will DOWNGRADE your version of Cinna!"
+            exit_code="CN_DEV"
+        else
+            exit_code="CN_NUPD"
         fi
     else
         echo -e "${RED}${BOLD}Error: Cannot connect to the Cinna server. Cinna needs an internet connection to run. Try again later."
-        exit 1
+        exit_code="CN_NC"
+        if [ "$gui" = "false" ]; then
+            exit 1
+        fi
     fi
 }
 
@@ -117,12 +125,14 @@ function get_packages() {
                 done < "$package_name"
             else
                 echo -e "${RED}${BOLD}Error:${NC} File $package_name not found."
+                exit_code="CN_FNFND"
             fi
         else
             package_url="$REPO/repo/packages/$package_name"
 
             if [[ -f "$INSTALLDIRECTORY/$package_name" ]]; then
                 echo -e "Package ${GREEN}$package_name${NC} is already installed."
+                exit_code="CN_ALIN"
             else
                 if wget --spider "$package_url/$package_name" 2>/dev/null; then
                     mkdir -p "$INSTALLDIRECTORY"
@@ -141,8 +151,10 @@ function get_packages() {
 
                     chmod +x "$INSTALLDIRECTORY/$package_name"
                     echo -e "Package ${GREEN}$package_name${NC} installed successfully."
+                    exit_code="CN_SUC"
                 else
                     echo -e "${RED}${BOLD}Error:${NC} Package ${GREEN}$package_name${NC} not found."
+                    exit_code="CN_PNFND"
                 fi
             fi
         fi
@@ -159,8 +171,10 @@ function remove_packages() {
                 rm -r "$INSTALLDIRECTORY/$package_name-files"
             fi
             echo -e "Package ${GREEN}$package_name${NC} removed."
+            exit_code="CN_SUC"
         else
             echo -e "${RED}${BOLD}Error:${NC} Package ${GREEN}$package_name${NC} is not installed."
+            exit_code="CN_NINS"
         fi
     done
 }
@@ -194,11 +208,14 @@ function upgrade_package() {
             fi
             chmod +x "$INSTALLDIRECTORY/$package_name"
             echo -e "Package ${GREEN}$package_name${NC} upgraded successfully."
+            exit_code="CN_SUC"
         else
             echo -e "${RED}${BOLD}Error:${NC} Package ${GREEN}$package_name${NC} not found."
+            exit_code="CN_NFND"
         fi
     else
         echo -e "${RED}${BOLD}Error:${NC} Package ${GREEN}$package_name${NC} is not installed."
+        exit_code="CN_NINS"
     fi
 }
 
@@ -310,23 +327,146 @@ function list_packages() {
 }
 
 function cinna_gui() {
-    action=$(zenity --list --title="Cinna GUI" --text="Select an action" --column="Action" "Install" "Remove" "Upgrade" "Package Info")
-
+    gui="true"
+    action=$(zenity --list --title="Cinna GUI" --text="Cinna - Select an action" --column="Action" "Install" "Remove" "Upgrade" "Package Info")
+    [[ "$?" != "0" ]] && exit 1
     case $action in
         "Install")
+            check_for_updates >> /dev/null
+            case $exit_code in 
+                "CN_NUPD")
+                    :
+                    ;;
+                "CN_UPD")
+                    zenity --info --title="Success" --text="There's an update for Cinna! Update in the CLI."
+                    ;;
+                "CN_DEV")
+                    zenity --info --title="Success" --text="You're on a development version of Cinna."
+                    ;;
+                "CN_NC")
+                    zenity --error --title="Error" --text="No connection!"
+                    exit 1
+                    ;;
+                *)
+                    :
+                    ;;
+            esac
             package_name=$(zenity --entry --title="Install Package" --text="Enter the package name:")
-            get_packages "$package_name"
+            [[ "$?" != "0" ]] && exit 1
+            get_packages "$package_name" >> /dev/null
+            case $exit_code in
+                "CN_SUC")
+                    zenity --info --title="Success" --text="Package installed successfully."
+                    ;;
+                "CN_FNFND")
+                    zenity --error --title="Error" --text="Failed to install the package.\nFile $package_name not found."
+                    ;;
+                "CN_PNFND")
+                    zenity --error --title="Error" --text="Failed to install the package.\nPackage $package_name not found."
+                    ;;
+                "CN_ALIN")
+                    zenity --error --title="Error" --text="Failed to install the package.\nPackage $package_name is already installed."
+                    ;;
+                *)
+                    zenity --error --title="Error" --text="Failed to install the package.\nUnknown error."
+                    ;;
+            esac
             ;;
         "Remove")
+            check_for_updates >> /dev/null
+            case $exit_code in 
+                "CN_NUPD")
+                    :
+                    ;;
+                "CN_UPD")
+                    zenity --info --title="Success" --text="There's an update for Cinna! Update in the CLI."
+                    ;;
+                "CN_DEV")
+                    zenity --info --title="Success" --text="You're on a development version of Cinna."
+                    ;;
+                "CN_NC")
+                    zenity --error --title="Error" --text="No connection!"
+                    exit 1
+                    ;;
+                *)
+                    :
+                    ;;
+            esac
             package_name=$(zenity --entry --title="Remove Package" --text="Enter the package name:")
-            remove_packages "$package_name"
+            [[ "$?" != "0" ]] && exit 1
+            remove_packages "$package_name" >> /dev/null
+            case $exit_code in
+                "CN_SUC")
+                    zenity --info --title="Success" --text="Package removed successfully."
+                    ;;
+                "CN_NINS")
+                    zenity --error --title="Error" --text="Failed to install the package.\Package $package_name not installed."
+                    ;;
+                *)
+                    zenity --error --title="Error" --text="Failed to removed the package.\nUnknown error."
+                    ;;
+            esac
             ;;
         "Upgrade")
+            check_for_updates >> /dev/null
+            case $exit_code in 
+                "CN_NUPD")
+                    :
+                    ;;
+                "CN_UPD")
+                    zenity --info --title="Success" --text="There's an update for Cinna! Update in the CLI."
+                    ;;
+                "CN_DEV")
+                    zenity --info --title="Success" --text="You're on a development version of Cinna."
+                    ;;
+                "CN_NC")
+                    zenity --error --title="Error" --text="No connection!"
+                    exit 1
+                    ;;
+                *)
+                    :
+                    ;;
+            esac
             package_name=$(zenity --entry --title="Upgrade Package" --text="Enter the package name:")
-            upgrade_package "$package_name"
+            [[ "$?" != "0" ]] && exit 1
+            upgrade_package "$package_name" >> /dev/null
+            case $exit_code in
+                "CN_SUC")
+                    zenity --info --title="Success" --text="Package removed successfully."
+                    ;;
+                "CN_NINS")
+                    zenity --error --title="Error" --text="Failed to install the package.\Package $package_name not installed."
+                    ;;
+                "CN_NFND")
+                    zenity --error --title="Error" --text="Failed to install the package.\Package $package_name not found."
+                    ;;
+                *)
+                    zenity --error --title="Error" --text="Failed to removed the package.\nUnknown error."
+                    ;;
+            esac
             ;;
         "Package Info")
+            check_for_updates >> /dev/null
+            case $exit_code in 
+                "CN_NUPD")
+                    :
+                    ;;
+                "CN_UPD")
+                    zenity --info --title="Success" --text="There's an update for Cinna! Update in the CLI."
+                    ;;
+                "CN_DEV")
+                    zenity --info --title="Success" --text="You're on a development version of Cinna."
+                    ;;
+                "CN_NC")
+                    zenity --error --title="Error" --text="No connection!"
+                    exit 1
+                    ;;
+                *)
+                    :
+                    ;;
+            esac
             package_name=$(zenity --entry --title="Package Info" --text="Enter the package name:")
+            [[ "$?" != "0" ]] && exit 1
             info_package "$package_name"
             ;;
         *)
